moonseo:
  jwt:
    access-secret: "moonseo-access-secret-key-for-local-testing-only-1234567890"
    refresh-secret: "moonseo-refresh-secret-key-for-local-testing-only-1234567890"
    access-minutes: 60
    refresh-minutes: 10080